### ISSUE TITLE
Unable to use the candlestick chart

### ISSUE THREAD

**Issue by nabtron** [chartjs/chartjs-chart-financial#11]
Hi. I can't find a working code / sample to run the financial chart. The files included in sample are not available in the folder! 

Also, is it out of beta now? Thanks, really waiting!

**Comment by benmccann** [comment]
You need to build it for the samples to work. I've updated the README to clarify

Not out of beta or released yet. We're working on improving chart.js itself to add features that we need. There's currently a PR pending there to add support for a timeseries scale.

**Comment by nabtron** [comment]
@benmccann I still don't get it how to built it or use it? Can you please point me to the right direction? Thanks

**Comment by benmccann** [comment]
The readme has instructions for building
